name: tsx-aggregator

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: tsx-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tsx-data-network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: tsx-pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - tsx-data-network

volumes:
  postgres-data:
    driver: local

networks:
  tsx-data-network:
